# Aigis will run from same directory where this config file resides
# All paths should be relative to there
name: Styleguide

# The directory containing the source files to parse recursively
source:
  - ./src/docs
  - ./.tmp_src/docs

# The types that aigis will scan to document comment
source_type:
  - .scss
  - .md
  - .css

# The directory that aigis will build to
dest: ./docs

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./src/assets
  - ./.tmp_src/assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./src/template_jade
template_engine: jade

# When you don't want color palette page (color.html) you may set false
color_palette: false

preview_class: 'pepagis-preview'

output_collection:
  - document
  - library
  - framework

transform:
  - html
  - jade

highlight: true
highlight_theme: monokai
